### ISSUE TITLE
Gemma3 - TypeError: PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'images'

### ISSUE THREAD

**Issue by alexl4321** [Blaizzy/mlx-vlm#238]
On Macos 15.2 with fresh python3.11 venv the example

python3.11 -m venv venv
source venv/bin/activate
pip install -U mlx-vlm

python -m mlx_vlm.generate --model mlx-community/gemma-3-4b-it-bf16 --max-tokens 100 --temperature 0.0 --prompt "Describe this image." --image ../images/image.jpeg

fails with

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/germma3/venv/lib/python3.11/site-packages/mlx_vlm/generate.py", line 156, in <module>
    main()
  File "/germma3/venv/lib/python3.11/site-packages/mlx_vlm/generate.py", line 141, in main
    output = generate(
             ^^^^^^^^^
  File "/germma3/venv/lib/python3.11/site-packages/mlx_vlm/utils.py", line 1117, in generate
    for response in stream_generate(model, processor, prompt, image, **kwargs):
  File "/germma3/venv/lib/python3.11/site-packages/mlx_vlm/utils.py", line 1018, in stream_generate
    inputs = prepare_inputs(
             ^^^^^^^^^^^^^^^
  File "/germma3/venv/lib/python3.11/site-packages/mlx_vlm/utils.py", line 814, in prepare_inputs
    inputs = processor(
             ^^^^^^^^^^
  File "/germma3/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2877, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/germma3/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2987, in _call_one
    return self.encode_plus(
           ^^^^^^^^^^^^^^^^^
  File "/germma3/venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 3063, in encode_plus
    return self._encode_plus(
           ^^^^^^^^^^^^^^^^^^
  File "/germma3/venv/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 613, in _encode_plus
    batched_output = self._batch_encode_plus(
                     ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PreTrainedTokenizerFast._batch_encode_plus() got an unexpected keyword argument 'images'

**Comment by Blaizzy** [comment]
You need to update your transformers :)

**Comment by magnusodman** [comment]
Same problem, using transformers 4.49.0. Latest release on pypi

**Comment by swlee60** [comment]
Installing the v4.49.0-Gemma-3 tagged version using the command:

```
pip install git+https://github.com/huggingface/transformers.git@1c0f782fe5f983727ff245c4c1b3906f9b99eec2 --no-cache-dir
```

Resolve this issue.

**Comment by asmeurer** [comment]
By the way, the "official" transformers tag is `v4.49.0-Gemma-3` So it would be 

```
pip install git+https://github.com/huggingface/transformers.git@v4.49.0-Gemma-3
```

(it's the exact same content but a different git commit. I don't think the transformers guys understand how to use git or packaging correctly)

**Comment by asmeurer** [comment]
I'm not sure if this is a mlx-vlm issue or a transformers tokenization issue, but (with the above transformers gemma3 tag), `<end_of_turn>` is not being correctly interpreted as a stop token. This causes it to generate infinite `<end_of_turn>` tokens until it reaches the max_tokens. 

```
$ python -m mlx_vlm.generate --model mlx-community/gemma-3-4b-it-bf16 --max-tokens 100 --temp 0.0 --prompt "What is the code on this vehicle??" --image https://farm8.staticflickr.com/7212/6896667434_2605d9e181_z.jpg
Fetching 10 files: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 76260.07it/s]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
==========
Files: ['https://farm8.staticflickr.com/7212/6896667434_2605d9e181_z.jpg']

Prompt: What is the code on this vehicle??<start_of_image>
The code on the aircraft in the image is D-EOJU.

Let me know if you'd like to know more about this aircraft.<end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn>
==========
Prompt: 269 tokens, 115.998 tokens-per-sec
Generation: 100 tokens, 9.037 tokens-per-sec
Peak memory: 12.887 GB
```

**Comment by arogister** [comment]
I confirm that transformers have to be updated and that a list of <end_of_turn> tokens is generated but not streamed, resulting in a long pause if setting max_tokens to a high value such as 1000 or 2000.

**Comment by JoeJoe1313** [comment]
@arogister, with the following package version

```
transformers @ git+https://github.com/huggingface/transformers@46350f5eae87ac1d168ddfdc57a0b39b64b9a029
```

I get the following output when setting `verbose=True` in `generate(model, processor, formatted_prompt, image, verbose=True, max_tokens=50)`:

```
==========
Files: <PIL.Image.Image image mode=RGB size=400x400 at 0x17CE9DC90> 

Prompt: What animal is in the image?<start_of_image>
The image shows a black cat. It has green eyes and a sign in front of it that says "HELLO PALIGEMMA 2".<end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn>
==========
Prompt: 268 tokens, 13.805 tokens-per-sec
Generation: 50 tokens, 1.451 tokens-per-sec
Peak memory: 15.469 GB
```

But if I set `verbose=False` the generation seems to become extremely slow. @asmeurer do you notice the same behaviour?

**Comment by JoeJoe1313** [comment]
@Blaizzy, it seems the model has two eos token ids in `eos_token_id` in the `config.json`:

```
"eos_token_id": [
        1,
        106
    ],
``` 

In `stream_generate` the break condition is

```
if token == tokenizer.eos_token_id:
            break
```

but `<end_of_turn>` is 106, and `tokenizer.eos_token_id` is `1` which is `<eos>`.

**Comment by dacox** [comment]
After updating to the gemma specific transfomers, I am able to run

```
$ python -m mlx_vlm.generate --model mlx-community/gemma-3-4b-it-4bit --max-tokens 100 --temp 0.0 --prompt "What is the code on this vehicle??" --image https://farm8.staticflickr.com/7212/6896667434_2605d9e181_z.jpg

==========
Files: ['https://farm8.staticflickr.com/7212/6896667434_2605d9e181_z.jpg']

Prompt: What is the code on this vehicle??<start_of_image>
Based on the image, the code on this vehicle is D-EOJU.

The aircraft in the image is a Cessna 152. The registration code is D-EOJU.

The registration code is D-EOJU.

The code on this vehicle is D-EOJU.

The code on this vehicle is D-EOJU.

The code on this vehicle is D-EOJU.

The code on this vehicle is D-EOJU.

The code
==========
Prompt: 269 tokens, 94.090 tokens-per-sec
Generation: 100 tokens, 43.273 tokens-per-sec
Peak memory: 5.124 GB
```


However, when _not_providing an image, i get

```
$ python -m mlx_vlm.generate --model mlx-community/gemma-3-4b-it-4bit --max-tokens 100 --temp 0.0 --prompt "What is a cat?"

==========
Files: []

Prompt: What is a cat?
<pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad><pad>
==========
Prompt: 6 tokens, 51.401 tokens-per-sec
Generation: 100 tokens, 55.945 tokens-per-sec
Peak memory: 3.118 GB
```

**Comment by Blaizzy** [comment]
There is a patch missing. 

I will add it as soon as possible

**Comment by damian0815** [comment]
I'm seeing the repeated token issue with `gemma-3-27b-pt-8bit` even when passing an image:

```
(.venv) mlx-vlm % python -m mlx_vlm.generate --model mlx-community/gemma-3-27b-pt-8bit --max-tokens 100 --temp 0.0   --prompt "What is the code on this vehicle??" --image https://farm8.staticflickr.com/7212/6896667434_2605d9e181_z.jpg

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Fetching 14 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 21837.21it/s]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
==========
Files: ['https://farm8.staticflickr.com/7212/6896667434_2605d9e181_z.jpg'] 

Prompt: What is the code on this vehicle??<start_of_image>
<start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image><start_of_image>
==========
Prompt: 269 tokens, 50.954 tokens-per-sec
Generation: 100 tokens, 6.263 tokens-per-sec
Peak memory: 31.695 GB
```

**Comment by d-r-w** [comment]
While Prince is resting:

I adjusted my locally cached `tokenizer_config.json` (mine is under `~/.cache/huggingface/hub/models--mlx-community--gemma-3-27b-it-8bit/snapshots/<hash>/tokenizer_config.json`)

Changed:
```
"eos_token": "<eos>",
```

To:
```
"eos_token": "<end_of_turn>",
```

Not sure if it's meant to handle both tokens but this seems to fix the issue for the time being ¯\_(ツ)_/¯

**Comment by Blaizzy** [comment]
Thanks guys!

This was fixed in v0.1.18

> pip install -U mlx-vlm 

https://github.com/Blaizzy/mlx-vlm/releases/tag/v0.1.18

**Comment by piercelamb** [comment]
I am on mlx-vlm 0.1.23 and transformers 4.51.3 and still having this problem (on Gemma 3 27b QAT 4bit).  My prompt is simply "hi how are you" with no images and I get <end_of_turn> until it reaches the max_tokens limit

@d-r-w 's solution worked for me however

**Comment by Blaizzy** [comment]
This PR should fix it: 

https://github.com/Blaizzy/mlx-vlm/pull/307
