### ISSUE TITLE
Gemma3 endless outputing

### ISSUE THREAD

**Issue by mccatec** [Blaizzy/mlx-vlm#244]
Is there a way to add customized end tokens to terminate generation by "python -m mlx_vlm.generate"?

(base)  ~/Downloads/ python -m mlx_vlm.generate --model gemma-3-12b-it-4bit --max-tokens 512 --temperature 0.0 --prompt "Describe this image." --image ../Pictures/watch.jpg 
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
==========
Files: ['../Pictures/watch.jpg'] 

Prompt: Describe this image.<start_of_image>
Here's a breakdown of the image:

**Overall Impression:**

The image is a close-up, top-down shot of a person's wrist wearing a wristwatch. The background is a wooden floor with a warm, natural tone.

**Details:**

*   **Wrist and Hand:** The person's wrist and part of their hand are visible. The skin tone appears to be light.
*   **Watch:** The focus is on the wristwatch. It has a black dial with white hour markers and hands. The bezel is a dark color with a rotating function. The watch is paired with a striped nylon strap.
*   **Background:** The background is a wooden floor with a visible grain pattern. The wood appears to be a light brown color.

**Style and Composition:**

*   **Close-up:** The image is a close-up shot, which emphasizes the watch and the person's wrist.
*   **Top-down perspective:** The camera angle is directly above the wrist, providing a clear view of the watch.
*   **Warm tones:** The wooden floor creates a warm and inviting atmosphere.<end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn><end_of_turn>
==========
Prompt: 265 tokens, 19.173 tokens-per-sec
Generation: 512 tokens, 14.229 tokens-per-sec
Peak memory: 9.184 GB

**Comment by d-r-w** [comment]
https://github.com/Blaizzy/mlx-vlm/issues/238#issuecomment-2727886437

Overlapping conversations, but hopefully this can help you use the model for the time being

**Comment by Blaizzy** [comment]
Thanks for reporting!

This was fixed in v0.1.18 and the models on the hub where refreshed.

> pip install -U mlx-vlm

https://github.com/Blaizzy/mlx-vlm/releases/tag/v0.1.18

**Comment by brettp** [comment]
Thanks for the fixes, @Blaizzy . This still appears to be an issue in v0.1.18 with the latest models from HF. The problem is that Gemma 3 outputs `<end_of_turn>` (106) tokens instead of `<eos>` (1). It continuously generates `<end_of_turn>` until max tokens is reached. Can verify by editing [utils.py](https://github.com/Blaizzy/mlx-vlm/blob/main/mlx_vlm/utils.py#L1047) to add:

```
        print(f"Is {token} == {tokenizer.eos_token_id}?")
        if token == tokenizer.eos_token_id:
            break
```

and then see:

```
$ mlx_vlm.generate --model mlx-community/gemma-3-27b-it-8bit --temp 0.0 --prompt "You must only answer with a single word. What is two plus two?" 
Fetching 17 files: 100%|███████████████████████████████████████████████████████████████| 17/17 [00:00<00:00, 60070.07it/s]
Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.48, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.
==========
Files: [] 

Prompt: <bos><start_of_turn>user
You must only answer with a single word. What is two plus two?<end_of_turn>
<start_of_turn>model

Is 26391 == 1?
Is 236761 == 1?
Is 106 == 1?
[snip 248 lines]
Is 106 == 1?
Four.<end_of_turn>[snip 252]<end_of_turn>
==========
Prompt: 25 tokens, 52.590 tokens-per-sec
Generation: 256 tokens, 15.478 tokens-per-sec
Peak memory: 29.824 GB
```
